In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.4.4


In [21]:
!pip install --upgrade numpy

# Creating Arrays from list

In [21]:
list=[1.2,2,3,4,5]
x=np.array(list)
print(x)

[1.2 2.  3.  4.  5. ]


In [23]:
# check the shape
x.shape

(5,)

In [25]:
# check the type
x.dtype

dtype('float64')

In [29]:
y=np.array([1,2,3,4,5])
print(y)

[1 2 3 4 5]


# np.zeros()

In [33]:
z=np.zeros(6)
print(z)

[0. 0. 0. 0. 0. 0.]


# np.ones()

In [37]:
a=np.ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


# 1D array

# np.arange

In [43]:
z=np.arange(0,10,2)
print(z)

[0 2 4 6 8]


# np.linspace

In [57]:
z=np.linspace(0,10,20)
print(z)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


# 2D array

In [90]:
# 2D 有2个中括号
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [68]:
a.shape

(2, 3)

# 3D array

In [110]:
# 3D 有3个中括号
# 2x2 with 3depth
a3=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [96]:
a3.shape

(3, 2, 2)

In [100]:
a3.ndim

3

In [104]:
a3.size

12

In [112]:
# 2x3 with 2depth
a4=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
print(a4)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
# Array Attributes

In [114]:
a4.shape

(2, 2, 3)

In [116]:
a4.size

12

In [118]:
a4.dtype

dtype('int64')

In [120]:
a4.ndim

3

# Array Indexing(start from zero 0)

In [126]:
a1=np.array([1,2,3,4,5])
print(a1[2])

3


In [134]:
a2=np.array([[1,2,3],[3,4,5]])
print(a2[1,1])

4


In [138]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3[1,0,1])

8


In [156]:
a4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a4[1,0,0])

5


# fancy indexing

In [169]:
a1=np.array([1,2,3,4,5])
print(a1[[2,4]])

[3 5]


In [179]:
a2=np.array([[1,2,3],[3,4,5]])
print(a2[[0,1]]) #call row
print(a2[:,[0,1]]) # call column

[[1 2 3]
 [3 4 5]]
[[1 2]
 [3 4]]


In [185]:
a1=np.array([1,2,3,4,5])
cond=a1>2
print(a1[cond])

[3 4 5]


In [199]:
a2=np.array([[1,2,3],[3,4,5]])
cond=(a2>2)&(a2<5)
a2[cond]

array([3, 3, 4])

# Array Slicing

# 1D

In [219]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1[1:10:2]

array([ 2,  4,  6,  8, 10])

In [225]:
print(a1[:5])
print(a1[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


# 2D

In [229]:
a2=np.array([[1,2,3],[3,4,5]])
a2[0,1:3]

array([2, 3])

In [253]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a3[:,1:2,:2]

array([[[ 4,  5]],

       [[10, 11]]])

In [255]:
a3[:,:1,:]

array([[[1, 2, 3]],

       [[7, 8, 9]]])

# Array Manipulations

In [274]:
# reshape()
a=np.array([1,2,3,4,5,6])
a=a.reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [286]:
# concatenate()  一定要2个括号
a1=np.array([1,2,3])
a2=np.array([2,3,4])
np.concatenate((a1,a2),axis=0)

array([1, 2, 3, 2, 3, 4])

In [290]:
# 垂直
a3=np.array([[1,2],[3,4]])
a4=np.array([[5,6],[7,8]])
np.concatenate((a3,a4),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [292]:
# 水平
np.concatenate((a3,a4),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [294]:
# stack
# 垂直
a3=np.array([[1,2],[3,4]])
a4=np.array([[5,6],[7,8]])
np.vstack((a3,a4))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [296]:
# 水平
np.hstack((a3,a4))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [307]:
# split
a=np.array([1,2,3,4,5,6])
np.split(a,3,axis=0)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [313]:
a3=np.array([[1,2],[3,4]])
np.split(a3,2,axis=0)

[array([[1, 2]]), array([[3, 4]])]

In [315]:
a3=np.array([[1,2],[3,4]])
np.split(a3,2,axis=1)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [319]:
a3=np.array([[1,2],[3,4]])
np.hsplit(a3,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [334]:
arr=np.arange(18).reshape(3,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [354]:
np.split(arr,3,axis=1)

[array([[[ 0,  1]],
 
        [[ 6,  7]],
 
        [[12, 13]]]),
 array([[[ 2,  3]],
 
        [[ 8,  9]],
 
        [[14, 15]]]),
 array([[[ 4,  5]],
 
        [[10, 11]],
 
        [[16, 17]]])]

In [350]:
np.split(arr,2,axis=2)

[array([[[ 0],
         [ 2],
         [ 4]],
 
        [[ 6],
         [ 8],
         [10]],
 
        [[12],
         [14],
         [16]]]),
 array([[[ 1],
         [ 3],
         [ 5]],
 
        [[ 7],
         [ 9],
         [11]],
 
        [[13],
         [15],
         [17]]])]

In [356]:
np.vsplit(arr,3)

[array([[[0, 1],
         [2, 3],
         [4, 5]]]),
 array([[[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 array([[[12, 13],
         [14, 15],
         [16, 17]]])]

In [358]:
np.hsplit(arr,3)

[array([[[ 0,  1]],
 
        [[ 6,  7]],
 
        [[12, 13]]]),
 array([[[ 2,  3]],
 
        [[ 8,  9]],
 
        [[14, 15]]]),
 array([[[ 4,  5]],
 
        [[10, 11]],
 
        [[16, 17]]])]

# Ufunc

# unary ufunc(一元数组-对单个输入数组进行操作)

In [362]:
a=np.arange(0,5)
np.max(a)

np.int64(4)

In [366]:
# argmax 是给位置
a=np.array([2,3,4,1,7,50])
np.argmax(a)

np.int64(5)

In [368]:
# max 是给数值
np.max(a)

np.int64(50)

# binary ufunc(对两个输入数组进行操作)

In [378]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.zeros(3)
np.add(a,b,out=c)

array([5., 7., 9.])

In [384]:
c=a+b
c

array([5, 7, 9])

# View and Copy

# View

In [416]:
arr=np.arange(5)
print(arr)
view_arr=arr[1:4] #basic slicing
print(view_arr)
view_arr[0]=999
print("Array after tempering:")
print("view array")
print(arr)
print("original array")
print(view_arr)

[0 1 2 3 4]
[1 2 3]
Array after tempering:
view array
[  0 999   2   3   4]
original array
[999   2   3]


# copy

In [424]:
arr=np.arange(5)
print(arr)
copy_arr=arr[1:4].copy()
print(view_arr)
copy_arr[0]=999
print("Array after tempering:")
print("original array")
print(arr)
print("copy array")
print(copy_arr)

[0 1 2 3 4]
[999   2   3]
Array after tempering:
original array
[0 1 2 3 4]
copy array
[999   2   3]


In [434]:
arr=np.arange(5)
print(arr)
view_arr=arr[[2,3,4]] # fancy indexing
#view_arr=arr[[2,3,4]].copy()
print(view_arr)
view_arr[0]=999
print("Array after tempering:")
print("view array")
print(arr)
print("original array")
print(view_arr)

[0 1 2 3 4]
[2 3 4]
Array after tempering:
view array
[0 1 2 3 4]
original array
[999   3   4]


# Excercise

In [436]:
grades=np.array([85,92,78,95,88,76,91,83])
print("Grades",grades)

Grades [85 92 78 95 88 76 91 83]


In [446]:
# who got A(>=80)
mark_a=np.where(grades>=80)
print(grades[mark_a])
print(mark_a)

[85 92 95 88 91 83]
(array([0, 1, 3, 4, 6, 7]),)


In [460]:
# number of students who got grade>=90
mark_best=np.where(grades>=90)
print(grades[mark_best])
np.sum(grades>=90)

[92 95 91]


np.int64(3)

In [464]:
# number of students who got grade>=90
mark_best=grades[(grades>=90)]
mark_best.size

3

In [466]:
# find the student with top mark
np.argmax(grades)

np.int64(3)